# Generated by Django 2.0.5 on 2018-05-29 17:27

from django.db import migrations
import elearning.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_content_file_image_text_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=elearning.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=elearning.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
